---
# Source: nginx-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: appdemorong-nginx-app
  labels:
    app.kubernetes.io/name: nginx-app
    helm.sh/chart: nginx-app-0.1.0
    app.kubernetes.io/instance: appdemorong
    app.kubernetes.io/managed-by: Tiller
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx-app
    app.kubernetes.io/instance: appdemorong

---
# Source: nginx-app/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: appdemorong-nginx-app
  labels:
    app.kubernetes.io/name: nginx-app
    helm.sh/chart: nginx-app-0.1.0
    app.kubernetes.io/instance: appdemorong
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-app
      app.kubernetes.io/instance: appdemorong
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-app
        app.kubernetes.io/instance: appdemorong
    spec:
      containers:
        - name: nginx-app
          image: openresty/openresty
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
            

---
# Source: nginx-app/templates/ingress.yaml


